= MicroProfile continued and Data stores

== Prerequisites

[source,bash]
----
docker pull postgres:14.0
docker pull mongo:5.0.3
----

== 01 JAX-RS/MicroProfile REST client

* JAX-RS classic client - Tutorial - https://docs.jboss.org/resteasy/docs/3.0-beta-3/userguide/html/RESTEasy_Client_Framework.html

* Quarkus guide - https://quarkus.io/guides/rest-client-reactive
* Spec - https://github.com/eclipse/microprofile-rest-client
* Spec doc - https://github.com/eclipse/microprofile-rest-client/blob/master/spec/src/main/asciidoc/microprofile-rest-client-spec.asciidoc

== 02 MicroProfile Fault Tolerance

* Quarkus guide - https://quarkus.io/guides/microprofile-fault-tolerance
* Spec - https://github.com/eclipse/microprofile-fault-tolerance
* Spec doc - https://github.com/eclipse/microprofile-fault-tolerance/blob/master/spec/src/main/asciidoc/microprofile-fault-tolerance-spec.asciidoc

== 03 OpenTelemetry (MP Telemetry Tracing)

OpenTelemetry is successor of OpenTracing.

* Quarkus guide - https://quarkus.io/guides/opentelemetry
* Website - https://opentelemetry.io/

**otel-collector-config.yaml**

[source,yaml]
----
receivers:
  otlp:
    protocols:
      grpc:
        endpoint: otel-collector:4317

exporters:
  jaeger:
    endpoint: jaeger-all-in-one:14250
    tls:
      insecure: true

processors:
  batch:

extensions:
  health_check:

service:
  extensions: [health_check]
  pipelines:
    traces:
      receivers: [otlp]
      processors: [batch]
      exporters: [jaeger]
----

**docker-compose.yml**

[source,yaml]
----
version: "2"
services:

  # Jaeger
  jaeger-all-in-one:
    image: jaegertracing/all-in-one:latest
    ports:
      - "16686:16686"
      - "14268:14268"
      - "14250:14250"
  # Collector
  otel-collector:
    image: otel/opentelemetry-collector:latest
    command: ["--config=/etc/otel-collector-config.yaml"]
    volumes:
      - ./otel-collector-config.yaml:/etc/otel-collector-config.yaml:Z
    ports:
      - "13133:13133" # Health_check extension
      - "4317:4317"   # OTLP gRPC receiver
    depends_on:
      - jaeger-all-in-one
----

== 04 DB utilization with Panache

=== 4a Panache with the relational DB (PostgreSQL)

* Quarkus guide - https://quarkus.io/guides/hibernate-orm-panache
* JavaDoc - https://javadoc.io/doc/io.quarkus/quarkus-hibernate-orm-panache/latest/index.html

To run PostgreSQL locally:

[source,bash]
----
mkdir -p ${HOME}/postgres-data

docker run --rm \
        --name dev-postgres \
        -e POSTGRES_PASSWORD=pass \
        -v ${HOME}/postgres-data/:/var/lib/postgresql/data:Z \
        -p 5432:5432 \
        postgres:14.0
----

And to connect the client:

[source,bash]
----
psql -h localhost -U postgres -d pv217
----

==== Testing

Add following dependencies:

[source,java]
----
<dependency>
  <groupId>io.quarkus</groupId>
  <artifactId>quarkus-panache-mock</artifactId>
  <scope>test</scope>
</dependency>
<dependency>
  <groupId>io.quarkus</groupId>
  <artifactId>quarkus-test-h2</artifactId>
  <scope>test</scope>
</dependency>
<dependency>
  <groupId>io.quarkus</groupId>
  <artifactId>quarkus-jdbc-h2</artifactId>
  <scope>test</scope>
</dependency>
----

Note for repository pattern use this instead of `quarkus-panache-mock`:

[source,java]
----
<dependency>
  <groupId>io.quarkus</groupId>
  <artifactId>quarkus-junit5-mockito</artifactId>
  <scope>test</scope>
</dependency>
----

And following configuration:

[source,bash]
----
%test.quarkus.datasource.jdbc.url=jdbc:h2:tcp://localhost/mem:test
%test.quarkus.datasource.db-kind=h2
----

And to your `@QuarkusTest` class add:

[source,java]
----
@QuarkusTest
@QuarkusTestResource(H2DatabaseTestResource.class)
----

This will configure embedded H2 database for tests.

=== 4b Panache with the NoSQL DB (MongoDB)

Quarkus guide - https://quarkus.io/guides/mongodb-panache

To run MongoDB locally:

[source,bash]
----
docker run --rm \
        --name dev-mongo \
        -e MONGO_INITDB_ROOT_USERNAME=admin \
        -e MONGO_INITDB_ROOT_PASSWORD=pass \
        -v ${HOME}/mongo-data:/data/db/:Z \
        -p 27017:27017 \
        mongo:5.0.3
----

Connect client:

[source,bash]
----
mongosh -u admin -p pass --authenticationDatabase admin pv217
----

Your mongo properties in `application.properties` should be:

[source,bash]
----
# configure the MongoDB client for a replica set of two nodes
quarkus.mongodb.connection-string=mongodb://admin:pass@localhost:27017
# mandatory if you don't specify the name of the database using @MongoEntity
quarkus.mongodb.database=pv217
----

**Testing**

With mongo we don't have in memory variant like we had with H2. So we need to actually start mongo in tests. This can for sure be done by starting clean mongo instance in the background to which tests can connect to but it can also be done by a framework called https://www.testcontainers.org/[testcontainers]. Here is an https://github.com/quarkusio/quarkus-quickstarts/tree/main/mongodb-panache-quickstart/src/test/java/org/acme/mongodb/panache[example].

== 05 Docker compose (Podman compose)

In this directory you can find a file named `docker-compose.yml`. https://docs.docker.com/compose/[Docker-compose] is a tool that allows you to specify several containers that can be started/stopped/managed as a single unit with single command. So for instance, you can run following commands in the same directory where the `docker-compose.yml` is to:

* start all defined containers:
[source,bash]
----
$ docker-compose up
----
The logs will be all available the same terminal.

* start all containers in the background:
[source,bash]
----
$ docker-compose up -d
----
To get logs you can call docker or docker-compose:
[source,bash]
----
$ docker logs -f <container>
----

* to stop all containers:
[source,bash]
----
$ docker-compose down
----
and to also remove them:
[source,bash]
----
$ docker-compose down --rmi
----

== 99 OPTIONAL ------------------

== 06 MP OpenTracing

* Quarkus guide - https://quarkus.io/guides/opentracing
* Spec - https://github.com/eclipse/microprofile-opentracing
* Spec doc - https://github.com/eclipse/microprofile-opentracing/blob/master/spec/src/main/asciidoc/microprofile-opentracing-spec.asciidoc

== 07 REST data Panache

- Quarkus guide - https://quarkus.io/guides/rest-data-panache

