= MicroProfile

== Prerequisites

[source,bash]
----
docker pull prometheus:v2.14.0
docker pull grafana/grafana:6.4.4
docker pull postgres
docker pull mongo
----

== 01 What is MicroProfile?

https://microprofile.io/

== 02 JAX-RS and CDI recap

* https://github.com/xstefank/pv217-microservices/tree/master/02-quarkus#abbreviations-explanations

* https://quarkus.io/guides/rest-json#whats-different-from-jakarta-ee-development

== 03 JSON-B

* https://quarkus.io/guides/rest-json

* Tutorial - https://www.baeldung.com/java-json-binding-api
** in Quarkus you don't need anything else then quarkus-jsonb extension
* Specification - https://github.com/eclipse-ee4j/jsonb-api
* http://json-b.net/

== 04 JSON-P

* Tutorial - https://www.baeldung.com/jee7-json
* Specification - https://github.com/eclipse-ee4j/jsonp
* https://eclipse-ee4j.github.io/jsonp/

== 03 MicroProfile Config

* Quarkus guide - https://quarkus.io/guides/config
* Spec - https://github.com/eclipse/microprofile-config
* Spec doc - https://github.com/eclipse/microprofile-config/blob/master/spec/src/main/asciidoc/microprofile-config-spec.asciidoc

== 04 MicroProfile Health

* Quarkus guide - https://quarkus.io/guides/microprofile-health
* Spec - https://github.com/eclipse/microprofile-health
* Spec doc - https://github.com/eclipse/microprofile-health/blob/master/spec/src/main/asciidoc/microprofile-health-spec.adoc

== 05 MicroProfile Metrics

* Quarkus guide - https://quarkus.io/guides/microprofile-metrics
* Spec - https://github.com/eclipse/microprofile-metrics
* Spec doc - https://github.com/eclipse/microprofile-metrics/blob/master/spec/src/main/asciidoc/metrics_spec.adoc
* More detailed metrics quickstart - https://github.com/wildfly/quickstart/tree/master/microprofile-metrics

**Prometheus**

[source,bash]
----
docker run --rm --name prometheus -p 9090:9090 --network host \
-v /path/to/prometheus.yml:/etc/prometheus/prometheus.yml:Z prom/prometheus:v2.14.0 \
--config.file=/etc/prometheus/prometheus.yml
----

**Grafana**

[source,bash]
----
docker run --rm -p 3000:3000 --network host grafana/grafana:6.4.4
----

== 06 MicroProfile OpenAPI

* Quarkus guide - https://quarkus.io/guides/openapi-swaggerui
* Spec - https://github.com/eclipse/microprofile-open-api
* Spec doc - https://github.com/eclipse/microprofile-open-api/blob/master/spec/src/main/asciidoc/microprofile-openapi-spec.adoc

== 07 DB utilization with Panache

=== 7a Panache with the relational DB (PostgreSQL)

* Quarkus guide - https://quarkus.io/guides/hibernate-orm-panache
* JavaDoc - https://javadoc.io/doc/io.quarkus/quarkus-hibernate-orm-panache/latest/index.html

To run PostgreSQL locally:

[source,bash]
----
mkdir -p ${HOME}/postgres-data

docker run --rm \
        --name dev-postgres \
        -e POSTGRES_PASSWORD=pass \
        -v ${HOME}/postgres-data/:/var/lib/postgresql/data:Z \
        -p 5432:5432 \
        postgres
----

And to connect the client:

[source,bash]
----
psql -h localhost -U postgres
----

==== Testing

Add following dependencies:

[source,java]
----
<dependency>
  <groupId>io.quarkus</groupId>
  <artifactId>quarkus-panache-mock</artifactId>
  <scope>test</scope>
</dependency>
<dependency>
  <groupId>io.quarkus</groupId>
  <artifactId>quarkus-test-h2</artifactId>
  <scope>test</scope>
</dependency>
<dependency>
  <groupId>io.quarkus</groupId>
  <artifactId>quarkus-jdbc-h2</artifactId>
  <scope>test</scope>
</dependency>
----

Note for repository pattern use this instead of `quarkus-panache-mock`:

[source,java]
----
<dependency>
  <groupId>io.quarkus</groupId>
  <artifactId>quarkus-junit5-mockito</artifactId>
  <scope>test</scope>
</dependency>
----

And following configuration:

[source,bash]
----
%test.quarkus.datasource.jdbc.url=jdbc:h2:tcp://localhost/mem:test
%test.quarkus.datasource.db-kind=h2
----

And to your `@QuarkusTest` class add:

[source,java]
----
@QuarkusTest
@QuarkusTestResource(H2DatabaseTestResource.class)
----

This will configure embedded H2 database for tests.

=== 7b Panache with the NoSQL DB (MongoDB)

Quarkus guide - https://quarkus.io/guides/mongodb-panache

To run MongoDB locally:

[source,bash]
----
docker run --rm \
        --name dev-mongo \
        -e MONGO_INITDB_ROOT_USERNAME=mongo \
        -e MONGO_INITDB_ROOT_PASSWORD=pass \
        -v ${HOME}/mongo-data:/data/db/:Z \
        -p 27017:27017 \
        mongo
----

Connect client:

[source,bash]
----
mongo --host localhost -u mongo -p pass --authenticationDatabase admin pv217
----

NOTE: Use the `admin` database. Otherwise the client can't authenticate.

== 8 Testing in Quarkus

Tutorial - https://www.baeldung.com/java-quarkus-testing
