version: "2.1"

services:

  postgres-avenger:
    image: postgres
    container_name: dev-postgres
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_PASSWORD=pass
    volumes:
      - ${HOME}/postgres-data/:/var/lib/postgresql/data:Z

  mongodb-snap:
    image: mongo
    container_name: dev-mongo
    ports:
      - "27017:27017"
    environment:
      - MONGO_INITDB_ROOT_USERNAME=mongo
      - MONGO_INITDB_ROOT_PASSWORD=pass
    volumes:
      - ${HOME}/mongo-data:/data/db/:Z
    privileged: true


#  zookeeper:
#    image: strimzi/kafka:0.19.0-kafka-2.5.0
#    command: [
#        "sh", "-c",
#        "bin/zookeeper-server-start.sh config/zookeeper.properties"
#    ]
#    ports:
#      - "2181:2181"
#    environment:
#      LOG_DIR: /tmp/logs
#
#  kafka:
#    image: strimzi/kafka:0.19.0-kafka-2.5.0
#    command: [
#        "sh", "-c",
#        "bin/kafka-server-start.sh config/server.properties --override listeners=PLAINTEXT://0.0.0.0:9092 --override advertised.listeners=PLAINTEXT://localhost:9092 --override zookeeper.connect=zookeeper:2181"
#    ]
#    depends_on:
#      - zookeeper
#    ports:
#      - "9092:9092"
#    environment:
#      LOG_DIR: "/tmp/logs"
