version: "3.8"

# postgres 5432
# mongo 27017
# prometheus 9090
# grafana 3000 (admin:admin)
# jaeger 16686 14268 14250 4317 4318
# keycloak 8180 (admin:admin)

services:

  prometheus:
    image: prom/prometheus:v2.39.1
    container_name: prometheus
    command: "--config.file=/etc/prometheus/prometheus.yml"
    volumes:
      - ./prometheus.yml:/etc/prometheus/prometheus.yml:Z
    network_mode: host

  grafana:
    image: grafana/grafana:9.1.8
    container_name: grafana
    network_mode: host
    depends_on:
      - prometheus

  jaeger:
    image: jaegertracing/all-in-one:1.38.1
    container_name: jaeger
    network_mode: host
    environment:
      - "COLLECTOR_OTLP_ENABLED=true"