= Introduction to Quarkus

== 01 DB utilization with Panache

=== 01a Panache with the relational DB (PostgreSQL)

* Quarkus guide - https://quarkus.io/guides/hibernate-orm-panache
* JavaDoc - https://javadoc.io/doc/io.quarkus/quarkus-hibernate-orm-panache/latest/index.html

To run PostgreSQL locally:

[source,bash]
----
mkdir -p ${HOME}/postgres-data

docker run -it --rm=true --name database -p 5432:5432 -e POSTGRES_USER=quarkus -e POSTGRES_PASSWORD=quarkus -e POSTGRES_DB=quarkus postgres
----

And to connect the client:

[source,bash]
----
psql -h localhost -U quarkus -d quarkus
----

=== 01b Panache with the NoSQL DB (MongoDB)

Quarkus guide - https://quarkus.io/guides/mongodb-panache

To run MongoDB locally:

[source,bash]
----
docker run --rm \
        --name dev-mongo \
        -v ${HOME}/mongo-data:/data/db/:Z \
        -p 27017:27017 \
        mongo
----

Connect client:

[source,bash]
----
mongosh --port 40881 person
----

Your mongo properties in `application.properties` should be:

[source,bash]
----
# configure the MongoDB client for a replica set of two nodes
%prod.quarkus.mongodb.connection-string=mongodb://admin:pass@localhost:27017
# mandatory if you don't specify the name of the database using @MongoEntity
quarkus.mongodb.database=quarkus
----

== 01c REST data Panache

- Quarkus guide - https://quarkus.io/guides/rest-data-panache

== 02 Micrometer (Metrics)

* Quarkus guide - https://quarkus.io/guides/micrometer
* Website - https://micrometer.io/

**Prometheus**

[source,bash]
----.
docker run --rm --name prometheus --network host \
-v /path/to/prometheus.yml:/etc/prometheus/prometheus.yml:Z prom/prometheus \
--config.file=/etc/prometheus/prometheus.yml
----

Example prometheus.yml is available link:./prometheus.yml[here].

**Grafana**

[source,bash]
----
docker run --rm -p 3000:3000 --network host grafana/grafana
----

== 03 OpenTelemetry (MP Telemetry Tracing)

OpenTelemetry is successor of OpenTracing.

* Quarkus guide - https://quarkus.io/guides/opentelemetry
* Website - https://opentelemetry.io/

**docker-compose.yml**

[source,yaml]
----
version: "3.8"

services:

  # Jaeger
  jaeger-all-in-one:
    image: jaegertracing/all-in-one:latest
    ports:
      - "16686:16686" # Jaeger UI
      - "14268:14268" # Receive legacy OpenTracing traces, optional
      - "4317:4317"   # OTLP gRPC receiver
      - "4318:4318"   # OTLP HTTP receiver, not yet used by Quarkus, optional
      - "14250:14250" # Receive from external otel-collector, optional
    environment:
      - COLLECTOR_OTLP_ENABLED=true
----

== 05 Security

* Quarkus guide OIDC - https://quarkus.io/guides/security-oidc-code-flow-authentication-tutorial
* Quarkus guide OIDC client and token propagation - https://quarkus.io/guides/security-openid-connect-client
* Quarkus guide Keycloak Devservices - https://quarkus.io/guides/security-openid-connect-dev-services

* Quarkus guide JWT - https://quarkus.io/guides/security-jwt
* Spec - https://github.com/eclipse/microprofile-jwt-auth
* Spec doc - https://github.com/eclipse/microprofile-jwt-auth/blob/master/spec/src/main/asciidoc/microprofile-jwt-auth-spec.asciidoc

**Additional**

* https://quarkus.io/guides/security-oidc-code-flow-authentication
* https://quarkus.io/guides/security-openid-connect-providers
 
* https://quarkus.io/guides/security-oidc-bearer-token-authentication-tutorial
* https://quarkus.io/guides/security-oidc-bearer-token-authentication

* https://quarkus.io/guides/security-openid-connect
* https://quarkus.io/guides/security-keycloak-authorization

**Keycloak**

[source,bash]
----
docker run --name keycloak -e KEYCLOAK_USER=admin -e KEYCLOAK_PASSWORD=admin -p 8180:8080 quay.io/keycloak/keycloak start-dev
----

