---
apiVersion: v1
kind: Service
metadata:
  annotations:
    app.quarkus.io/vcs-url: https://github.com/xstefank/pv217-microservices.git
    app.quarkus.io/build-timestamp: 2020-10-26 - 17:43:12 +0000
    app.quarkus.io/commit-id: fe73d5410237106d77fb381a0b40a5591f89383e
  labels:
    app.kubernetes.io/name: kubernetes-quickstart
    app.kubernetes.io/version: 1.0-SNAPSHOT
  name: kubernetes-quickstart
spec:
  ports:
  - name: http
    nodePort: 31556
    port: 8080
    targetPort: 8080
  selector:
    app.kubernetes.io/name: kubernetes-quickstart
    app.kubernetes.io/version: 1.0-SNAPSHOT
  type: NodePort
---
apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    app.quarkus.io/vcs-url: https://github.com/xstefank/pv217-microservices.git
    app.quarkus.io/build-timestamp: 2020-10-26 - 17:43:12 +0000
    app.quarkus.io/commit-id: fe73d5410237106d77fb381a0b40a5591f89383e
  labels:
    app.kubernetes.io/name: kubernetes-quickstart
    app.kubernetes.io/version: 1.0-SNAPSHOT
  name: kubernetes-quickstart
spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: kubernetes-quickstart
      app.kubernetes.io/version: 1.0-SNAPSHOT
  template:
    metadata:
      annotations:
        app.quarkus.io/vcs-url: https://github.com/xstefank/pv217-microservices.git
        app.quarkus.io/build-timestamp: 2020-10-26 - 17:43:12 +0000
        app.quarkus.io/commit-id: fe73d5410237106d77fb381a0b40a5591f89383e
      labels:
        app.kubernetes.io/name: kubernetes-quickstart
        app.kubernetes.io/version: 1.0-SNAPSHOT
    spec:
      containers:
      - env:
        - name: KUBERNETES_NAMESPACE
          valueFrom:
            fieldRef:
              fieldPath: metadata.namespace
        image: docker.io/xstefank/kubernetes-quickstart:1.0-SNAPSHOT
        imagePullPolicy: IfNotPresent
        name: kubernetes-quickstart
        ports:
        - containerPort: 8080
          name: http
          protocol: TCP
