= PV217 microservice Lecture 01

== Demo from lecture

We've build a simple Quarkus application that can be found in `pv217-service` folder.

=== Building

You can build the application with `./mvnw clean package`.

=== Testing

Dev mode for quick testing can be started with `./mvnw quarkus:dev`. You can then access the application at `http://localhost:8080/ping` to see the processed google page.

=== Docker/Podman image

You can follow the instructions in comments.

But the images should be build in your namespace if you want to push them to public repositories as Docker Hub. So I changed my commands like this:

1. `./mvnw package`
2. `podman build -f src/main/docker/Dockerfile.jvm -t xstefank/pv217-service-jvm .`
3. `podman push --format docker xstefank/pv217-service-jvm`

Image can then be found in Docker Hub at `https://hub.docker.com/repository/docker/xstefank/pv217-service-jvm`.

You can then run your image with:

`podman run -p 8080:8080 xstefank/pv217-service-jvm`

=== Consuming in OpenShift

CRC (code ready containers) or local OpenShift environment can be downloaded from https://developers.redhat.com/products/codeready-containers/overview?ts=1633525979003. You can also get a tempory public OS cluster in sandbox but this will be deleted in a few days. But it's good for testing.

CRC can be started with `crc start` (note that you should follow setup first in https://access.redhat.com/documentation/en-us/red_hat_codeready_containers/1.29/html/getting_started_guide/installation_gsg).

Then with your `oc` CLI tool (which should come with CRC, check the console output) or you can download it from https://docs.openshift.com/container-platform/4.7/cli_reference/openshift_cli/getting-started-cli.html#cli-installing-cli-on-linux_cli-developer-commands) you can run the following to deploy your image on openshift:

1. `oc new-project <project-name>`
2. `oc new-app xstefank/pv217-service-jvm`

This will deploy our application.

You can check if it is running with `oc get pods`.

Once running, you can expose it's internal URL for public access with:

1. `oc get svc`
2. `oc expose svc/<service-name>`
3. `oc get routes`

And access the `<route>/ping` in your browser.
