{
 "title": "PrimeCheckerDashboard",
 "time": { "from": "now-6h", "to": "now" },
 "refresh": "5s",
 "panels": [
  {
   "title": "performedChecks_total Counter",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "application_io_xstefank_metrics_PrimeResource_performedChecks_total",
     "legendFormat": "performedChecks_total"
    }
   ]
  },
  {
   "title": "application_checksTimer_mean_seconds",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "application_checksTimer_mean_seconds",
     "legendFormat": "application_checksTimer_mean_seconds"
    }
   ]
  },
  {
   "title": "Highest Prime So Far",
   "type": "gauge",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 8 },
   "targets": [
    {
     "expr": "application_io_xstefank_metrics_PrimeResource_highestPrimeNumberSoFar",
     "legendFormat": "Highest Prime so far"
    }
   ]
  },
  {
   "title": "Checks Timer",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 8 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "application_checksTimer_mean_seconds",
     "legendFormat": "Checks Timer Mean seconds"
    },
    {
     "expr": "application_checksTimer_max_seconds",
     "legendFormat": "Checks Timer Mean seconds"
    },
    {
     "expr": "application_checksTimer_min_seconds",
     "legendFormat": "Checks Timer Min seconds"
    }
   ]
  }
 ]
}