version: "3.7"

services:

  postgres-avenger:
    image: postgres
    container_name: dev-postgres
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_PASSWORD=pass
    volumes:
      - ${HOME}/postgres-data/:/var/lib/postgresql/data:Z

  mongodb-snap:
    image: mongo
    container_name: dev-mongo
    ports:
      - 27017:27017
    environment:
      - MONGO_INITDB_ROOT_USERNAME=root
      - MONGO_INITDB_ROOT_PASSWORD=pass
    volumes:
      - ${HOME}/mongo-data:/data/db/:Z
    privileged: true

